/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;

/**
 *
 * @author Cesar
 */
public class Calculadora_Proyect extends javax.swing.JFrame {

    public float primernumero;
    public float segundonumero;
    public String operador;
    public Calculadora_Proyect() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        Casilla = new javax.swing.JTextField();
        Tecla_1 = new javax.swing.JButton();
        Tecla_2 = new javax.swing.JButton();
        Tecla_3 = new javax.swing.JButton();
        Tecla_4 = new javax.swing.JButton();
        Tecla_5 = new javax.swing.JButton();
        Tecla_6 = new javax.swing.JButton();
        Tecla_7 = new javax.swing.JButton();
        Tecla_8 = new javax.swing.JButton();
        Tecla_9 = new javax.swing.JButton();
        Tecla_0 = new javax.swing.JButton();
        Tecla_Punto = new javax.swing.JButton();
        Tecla_Igual = new javax.swing.JButton();
        Tecla_Multiplicacion = new javax.swing.JButton();
        Tecla_Division = new javax.swing.JButton();
        Tecla_Mas = new javax.swing.JButton();
        Tecla_Menos = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        Historial = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Casilla.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        Tecla_1.setText("1");
        Tecla_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tecla_1ActionPerformed(evt);
            }
        });

        Tecla_2.setText("2");
        Tecla_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tecla_2ActionPerformed(evt);
            }
        });

        Tecla_3.setText("3");
        Tecla_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tecla_3ActionPerformed(evt);
            }
        });

        Tecla_4.setText("4");
        Tecla_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tecla_4ActionPerformed(evt);
            }
        });

        Tecla_5.setText("5");
        Tecla_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tecla_5ActionPerformed(evt);
            }
        });

        Tecla_6.setText("6");
        Tecla_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tecla_6ActionPerformed(evt);
            }
        });

        Tecla_7.setText("7");
        Tecla_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tecla_7ActionPerformed(evt);
            }
        });

        Tecla_8.setText("8");
        Tecla_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tecla_8ActionPerformed(evt);
            }
        });

        Tecla_9.setText("9");
        Tecla_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tecla_9ActionPerformed(evt);
            }
        });

        Tecla_0.setText("0");
        Tecla_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tecla_0ActionPerformed(evt);
            }
        });

        Tecla_Punto.setText(".");
        Tecla_Punto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tecla_PuntoActionPerformed(evt);
            }
        });

        Tecla_Igual.setText("=");
        Tecla_Igual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tecla_IgualActionPerformed(evt);
            }
        });

        Tecla_Multiplicacion.setText("*");
        Tecla_Multiplicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tecla_MultiplicacionActionPerformed(evt);
            }
        });

        Tecla_Division.setText("/");
        Tecla_Division.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tecla_DivisionActionPerformed(evt);
            }
        });

        Tecla_Mas.setText("+");
        Tecla_Mas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tecla_MasActionPerformed(evt);
            }
        });

        Tecla_Menos.setText("-");
        Tecla_Menos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tecla_MenosActionPerformed(evt);
            }
        });

        jMenu1.setText("Opciones");

        Historial.setText("Nuevo");
        Historial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HistorialActionPerformed(evt);
            }
        });
        jMenu1.add(Historial);

        jMenuItem3.setText("Historial");
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ayuda");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Casilla)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Tecla_1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Tecla_2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Tecla_3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(Tecla_7, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(Tecla_8, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(Tecla_9, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(Tecla_4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(Tecla_5, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(Tecla_6, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(Tecla_0, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(Tecla_Punto, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(Tecla_Igual, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Tecla_Mas, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(Tecla_Multiplicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Tecla_Menos, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Tecla_Division, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(Casilla, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Tecla_1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Tecla_2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Tecla_3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Tecla_4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Tecla_5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Tecla_6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Tecla_7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Tecla_8, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Tecla_9, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Tecla_0, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Tecla_Punto, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Tecla_Igual, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Tecla_Mas, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Tecla_Menos, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Tecla_Multiplicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Tecla_Division, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Tecla_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tecla_4ActionPerformed
        this.Casilla.setText(this.Casilla.getText()+"4");
    }//GEN-LAST:event_Tecla_4ActionPerformed

    private void Tecla_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tecla_8ActionPerformed
        this.Casilla.setText(this.Casilla.getText()+"8");
    }//GEN-LAST:event_Tecla_8ActionPerformed

    private void Tecla_IgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tecla_IgualActionPerformed
        this.segundonumero=Float.parseFloat(this.Casilla.getText());
        
        switch(this.operador){
            case "+":this.Casilla.setText(Float.toString(this.primernumero+this.segundonumero)); break;
            case "-":this.Casilla.setText(Float.toString(this.primernumero-this.segundonumero)); break;
            case "*":this.Casilla.setText(Float.toString(this.primernumero*this.segundonumero)); break;
            case "/":this.Casilla.setText(Float.toString(this.primernumero/this.segundonumero)); break;
        }
    }//GEN-LAST:event_Tecla_IgualActionPerformed

    private void Tecla_MasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tecla_MasActionPerformed
        this.primernumero=Float.parseFloat(this.Casilla.getText());
        this.operador="+";
        this.Casilla.setText("");
    }//GEN-LAST:event_Tecla_MasActionPerformed

    private void Tecla_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tecla_1ActionPerformed
        this.Casilla.setText(this.Casilla.getText()+"1");
        eventosdelteclado
        
    }//GEN-LAST:event_Tecla_1ActionPerformed

    private void Tecla_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tecla_2ActionPerformed
        this.Casilla.setText(this.Casilla.getText()+"2");
    }//GEN-LAST:event_Tecla_2ActionPerformed

    private void Tecla_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tecla_3ActionPerformed
        this.Casilla.setText(this.Casilla.getText()+"3");
    }//GEN-LAST:event_Tecla_3ActionPerformed

    private void Tecla_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tecla_5ActionPerformed
        this.Casilla.setText(this.Casilla.getText()+"5");
    }//GEN-LAST:event_Tecla_5ActionPerformed

    private void Tecla_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tecla_6ActionPerformed
        this.Casilla.setText(this.Casilla.getText()+"6");
    }//GEN-LAST:event_Tecla_6ActionPerformed

    private void Tecla_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tecla_7ActionPerformed
        this.Casilla.setText(this.Casilla.getText()+"7");
    }//GEN-LAST:event_Tecla_7ActionPerformed

    private void Tecla_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tecla_9ActionPerformed
        this.Casilla.setText(this.Casilla.getText()+"9");
    }//GEN-LAST:event_Tecla_9ActionPerformed

    private void Tecla_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tecla_0ActionPerformed
        this.Casilla.setText(this.Casilla.getText()+"0");
    }//GEN-LAST:event_Tecla_0ActionPerformed

    private void Tecla_MenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tecla_MenosActionPerformed
        this.primernumero=Float.parseFloat(this.Casilla.getText());
        this.operador="-";
        this.Casilla.setText("");
    }//GEN-LAST:event_Tecla_MenosActionPerformed

    private void Tecla_MultiplicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tecla_MultiplicacionActionPerformed
        this.primernumero=Float.parseFloat(this.Casilla.getText());
        this.operador="*";
        this.Casilla.setText("");
    }//GEN-LAST:event_Tecla_MultiplicacionActionPerformed

    private void Tecla_DivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tecla_DivisionActionPerformed
        this.primernumero=Float.parseFloat(this.Casilla.getText());
        this.operador="/";
        this.Casilla.setText("");
    }//GEN-LAST:event_Tecla_DivisionActionPerformed

    private void Tecla_PuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tecla_PuntoActionPerformed
        if(!(this.Casilla.getText().contains("."))){
            this.Casilla.setText(this.Casilla.getText()+".");
        }
    }//GEN-LAST:event_Tecla_PuntoActionPerformed

    private void HistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HistorialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HistorialActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora_Proyect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora_Proyect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora_Proyect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora_Proyect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora_Proyect().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Casilla;
    private javax.swing.JMenuItem Historial;
    private javax.swing.JButton Tecla_0;
    private javax.swing.JButton Tecla_1;
    private javax.swing.JButton Tecla_2;
    private javax.swing.JButton Tecla_3;
    private javax.swing.JButton Tecla_4;
    private javax.swing.JButton Tecla_5;
    private javax.swing.JButton Tecla_6;
    private javax.swing.JButton Tecla_7;
    private javax.swing.JButton Tecla_8;
    private javax.swing.JButton Tecla_9;
    private javax.swing.JButton Tecla_Division;
    private javax.swing.JButton Tecla_Igual;
    private javax.swing.JButton Tecla_Mas;
    private javax.swing.JButton Tecla_Menos;
    private javax.swing.JButton Tecla_Multiplicacion;
    private javax.swing.JButton Tecla_Punto;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    // End of variables declaration//GEN-END:variables
    private void eventosdelteclado(){
        KeyListener eventosteclado = new KeyListener() {
            @Override
            public void keyTyped(KeyEvent e) {
                throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
            }

            @Override
            public void keyPressed(KeyEvent e) {
                throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
            }

            @Override
            public void keyReleased(KeyEvent e) {
                throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
            }
        };
        tecla_1ActionPerformed.addKeyListener(eventosteclado);
    };
}

